### ISSUE TITLE
Issues with getting the audio analysis file to work correctly with Puppeteer

### ISSUE THREAD

**Issue by mikevercoelen** [jberg/butterchurn-video-creator#2]
Generating an audio file for me doesn't work correctly.

Did some debugging, and it never triggers the body of `$(function(() ...` 

Any tips on how I can get it to work?

Awesome job on Butterchurn, this is amazing

**Comment by jobez** [comment]
i just gave this a shot and i think it may have to do with this output i got:

> PAGE LOG:  The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

Also might be due to this: https://github.com/puppeteer/puppeteer/issues/5383 -- atleast that is what I think is causing issues with the `generateScreenshots.js` logic
